In [2]:
pip install tensorflow-text

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 MB 1.3 MB/s  0:00:43 eta 0:00:010:00:02
Note: you may need to restart the kernel to use updated packages.


In [3]:
import tensorflow_hub as hub
import tensorflow_text as text

In [4]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [5]:
bert_preprocess_model=hub.KerasLayer(preprocess_url)

In [7]:
text_test=['nice movie indeed','i love python programming']
text_preprocessed=bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [8]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [9]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [11]:
bert_model=hub.KerasLayer(encoder_url)
bert_results=bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['pooled_output', 'default', 'encoder_outputs', 'sequence_output'])

In [12]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177415, -0.21411926,  0.4976951 , ...,  0.24465191,
        -0.47334486,  0.8175871 ],
       [-0.9171231 , -0.47935167, -0.7865695 , ..., -0.6175173 ,
        -0.71026844,  0.921843  ]], dtype=float32)>

In [16]:
(bert_results['encoder_outputs'])

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901427,  0.00644747, -0.03614961, ...,  0.04999623,
           0.06149194, -0.02657565],
         [ 1.1753385 ,  1.2140787 ,  1.1569979 , ...,  0.11634387,
          -0.35855344, -0.40490198],
         [ 0.03859039,  0.5386995 , -0.21089831, ...,  0.21858215,
           0.72601706, -1.1158607 ],
         ...,
         [-0.07587018, -0.254219  ,  0.7075511 , ...,  0.5054203 ,
          -0.18878669,  0.15028353],
         [-0.1606661 , -0.280897  ,  0.5759708 , ...,  0.52758557,
          -0.11141348,  0.02887548],
         [-0.04428183, -0.20279601,  0.59093565, ...,  0.81338364,
          -0.39075816, -0.02601741]],
 
        [[ 0.18903586,  0.0275255 , -0.06513744, ..., -0.00620215,
           0.15053889,  0.03165443],
         [ 0.59161484,  0.75891376, -0.07240667, ...,  0.6190396 ,
           0.8292891 ,  0.16161942],
         [ 1.4460828 ,  0.44602636,  0.4099026 , ...,  0.48255885,
           0.6269114 ,  0.13